version: '3.6'
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  my-mongodb:
    image: mongo:latest
    container_name: kata-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: --serviceExecutor adaptive